type Journal = [string, string];
export const MAPPINGS = ([
    ["\\aas", "American Astronomical Society Meeting Abstracts"],
    ["\\aj", "Astronomical Journal"],
    ["\\actaa", "Acta Astronomica"],
    ["\\araa", "Annual Review of Astronomy and Astrophysics"],
    ["\\apj", "Astrophysical Journal"],
    ["\\apjl", "Astrophysical Journal, Letters"],
    ["\\apjs", "Astrophysical Journal, Supplement"],
    ["\\ao", "Applied Optics"],
    ["\\apss", "Astrophysics and Space Science"],
    ["\\aap", "Astronomy and Astrophysics"],
    ["\\aapr", "Astronomy and Astrophysics Reviews"],
    ["\\aaps", "Astronomy and Astrophysics, Supplement"],
    ["\\aplett", "Astrophysics Letters"],
    ["\\apspr", "Astrophysics Space Physics Research"],
    ["\\azh", "Astronomicheskii Zhurnal"],
    ["\\baas", "Bulletin of the AAS"],
    ["\\bain", "Bulletin Astronomical Institute of the Netherlands"],
    ["\\caa", "Chinese Astronomy and Astrophysics"],
    ["\\cjaa", "Chinese Journal of Astronomy and Astrophysics"],
    ["\\dps", "American Astronomical Society/Division for Planetary Sciences Meeting Abstracts"],
    ["\\fcp", "Fundamental Cosmic Physics"],
    ["\\gca", "Geochimica Cosmochimica Acta"],
    ["\\grl", "Geophysics Research Letters"],
    ["\\iaucirc", "IAU Cirulars"],
    ["\\icarus", "Icarus"],
    ["\\jaavso", "Journal of the American Association of Variable Star Observers"],
    ["\\jcap", "Journal of Cosmology and Astroparticle Physics"],
    ["\\jcp", "Journal of Chemical Physics"],
    ["\\jgr", "Journal of Geophysics Research"],
    ["\\jqsrt", "Journal of Quantitiative Spectroscopy and Radiative Transfer"],
    ["\\jrasc", "Journal of the RAS of Canada"],
    ["\\maps", "Meteoritics and Planetary Science"],
    ["\\memras", "Memoirs of the RAS"],
    ["\\memsai", "Mem. Societa Astronomica Italiana"],
    ["\\mnras", "Monthly Notices of the RAS"],
    ["\\na", "New Astronomy"],
    ["\\nar", "New Astronomy Review"],
    ["\\nat", "Nature"],
    ["\\nphysa", "Nuclear Physics A"],
    ["\\pasa", "Publications of the Astron. Soc. of Australia"],
    ["\\pasp", "Publications of the ASP"],
    ["\\pasj", "Publications of the ASJ"],
    ["\\physrep", "Physics Reports"],
    ["\\physscr", "Physica Scripta"],
    ["\\planss", "Planetary Space Science"],
    ["\\pra", "Physical Review A: General Physics"],
    ["\\prb", "Physical Review B: Solid State"],
    ["\\prc", "Physical Review C"],
    ["\\prd", "Physical Review D"],
    ["\\pre", "Physical Review E"],
    ["\\prl", "Physical Review Letters"],
    ["\\procspie", "Proceedings of the SPIE"],
    ["\\psj", "Planetary Science Journal"],
    ["\\qjras", "Quarterly Journal of the RAS"],
    ["\\rmxaa", "Revista Mexicana de Astronomia y Astrofisica"],
    ["\\skytel", "Sky and Telescope"],
    ["\\solphys", "Solar Physics"],
    ["\\sovast", "Soviet Astronomy"],
    ["\\ssr", "Space Science Reviews"],
    ["\\zap", "Zeitschrift fuer Astrophysik"],
] as Journal[]).sort((a, b) => b[0].length - a[0].length);

export function fixAstroJournalMacros(text: string): string {
    MAPPINGS.forEach(([macro, journal]) => {
        text = text.replace(macro, journal);
    });
    return text;
}