name: Publish

on:
  push:
    branches:
      - main
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: xvfb-run -a npm test
      - name: Publish pre-release
        if: success() && startsWith(github.ref, 'refs/tags/') && github.event.release.prerelease == true
        run: npm run prerelease
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Publish release
        if: success() && startsWith(github.ref, 'refs/tags/') && github.event.release.prerelease == false
        run: npm run release
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
